// Generated by LiveScript 1.5.0
(function(){
  var strategist, strategies;
  strategist = require('../../strategist.js');
  strategies = [require('./balance-eth-etherscan.js'), require('./balance-eth-etherchain.js')];
  module.exports = strategist(strategies);
}).call(this);
