// Generated by LiveScript 1.5.0
(function(){
  var request, cheerio, big, iserror;
  request = require('request');
  cheerio = require('cheerio');
  big = require('big.js');
  iserror = require('../iserror.js')('https://blockchain.info');
  module.exports = function(key, callback){
    return request("https://blockchain.info/address/" + key, function(err, response){
      var $, html, tr;
      if (iserror(err, "Failed to get balance of BTC address " + key)) {
        return callback(null);
      }
      $ = cheerio.load(response.body);
      html = $('#final_balance span').html();
      if (html == null) {
        return callback(null);
      }
      tr = $('#final_balance span').html().replace(/[^0-9.]/g, "");
      callback(err, big(tr));
    });
  };
}).call(this);
