// Generated by LiveScript 1.5.0
(function(){
  var request, bigNumber;
  request = require('request');
  bigNumber = require('big-number');
  module.exports = function(key, callback){
    return request("http://ltc.blockr.io/api/v1/address/info/" + key, function(err, response, body){
      var data, e;
      if (err != null) {
        return callback(null);
      }
      try {
        data = JSON.parse(body);
        callback(bigNumber(data.data.balance));
      } catch (e$) {
        e = e$;
        callback(null);
      }
    });
  };
}).call(this);
