// Generated by LiveScript 1.5.0
(function(){
  var request, bigNumber, iserror;
  request = require('request');
  bigNumber = require('big.js');
  iserror = require('../iserror.js');
  module.exports = function(key, callback){
    return request("http://ltc.blockr.io/api/v1/address/info/" + key, function(err, response, body){
      var data;
      if (iserror(err, "Balance ltc " + key)) {
        return callback(null);
      }
      data = JSON.parse(body);
      callback(bigNumber(data.data.balance));
    });
  };
}).call(this);
