// Generated by LiveScript 1.5.0
(function(){
  var request, bigNumber;
  request = require('request');
  bigNumber = require('big.js');
  module.exports = function(key, callback){
    return request("http://ltc.blockr.io/api/v1/address/info/" + key, function(err, response, body){
      var data;
      if (err != null) {
        return callback(null);
      }
      data = JSON.parse(body);
      callback(bigNumber(data.data.balance));
    });
  };
}).call(this);
