// Generated by LiveScript 1.5.0
(function(){
  var main, bigNumber, p, expect, allCoins, slice$ = [].slice;
  main = require('../main/main.js');
  bigNumber = require('big.js');
  p = require('prelude-ls');
  expect = require('expect');
  allCoins = ['eth', 'btc', 'ltc'];
  describe('Basic', function(){
    it('exists', function(){
      var i$, ref$, len$, coin, provider, results$ = [];
      for (i$ = 0, len$ = (ref$ = allCoins).length; i$ < len$; ++i$) {
        coin = ref$[i$];
        provider = main.newAddr[coin];
        expect(provider().address).toBeA("string", "Not string Address " + coin);
        results$.push(expect(provider().privateKey).toBeA("string", "Not string Private Key " + coin));
      }
      return results$;
    });
    it('unique', function(){
      var i$, ref$, len$, coin, provider, results$ = [];
      for (i$ = 0, len$ = (ref$ = allCoins).length; i$ < len$; ++i$) {
        coin = ref$[i$];
        provider = main.newAddr[coin];
        expect(provider().address).toNotBe(provider().address, "Not unique Private Key " + coin);
        results$.push(expect(provider().privateKey).toNotBe(provider().privateKey, "Not unique Private Key " + coin));
      }
      return results$;
    });
    it('valid', function(){
      var i$, ref$, len$, coin, provider, ref1$, address, privateKey, valid, message, signature, results$ = [];
      for (i$ = 0, len$ = (ref$ = allCoins).length; i$ < len$; ++i$) {
        coin = ref$[i$];
        provider = main.newAddr[coin];
        ref1$ = provider(), address = ref1$.address, privateKey = ref1$.privateKey;
        valid = provider.verify(address);
        expect(valid).toBe(true, "Invalid Ethereum Address " + coin);
        message = "Test Message";
        signature = main.sign[coin].sign(message, privateKey);
        results$.push(expect(main.sign[coin].verify(message, address, signature)).toBe(true));
      }
      return results$;
    });
    it('balance', function(done){
      var accs, checkBalance, checkBalances;
      this.timeout(25000);
      accs = {
        eth: {
          address: "0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe",
          balance: bigNumber("802672.276608465139479303")
        },
        ltc: {
          address: "34Ae29qWAhGGTw3cSNkPygiwsgKbbCatou",
          balance: bigNumber("402474.2484")
        },
        btc: {
          address: '1HQ3Go3ggs8pFnXuHVHRytPCq5fGG8Hbhx',
          balance: bigNumber("69370.10701994")
        }
      };
      checkBalance = function(coin, cb){
        var acc, provider;
        acc = accs[coin];
        provider = main.balance[coin];
        return provider(acc.address, function(err, balance){
          console.log('balance', err, balance);
          try {
            expect(err).toBe(null);
            expect(balance).toNotBe(null, "Balance is null for " + coin);
            expect(balance.eq(acc.balance)).toBe(true, "real balance " + balance.toString() + " is not expected " + acc.balance.toString() + " for " + coin);
            cb(null);
          } catch (e$) {
            err = e$;
            cb(err);
          }
        });
      };
      checkBalances = function(coins, cb){
        if (coins.length === 0) {
          return cb(null);
        }
        return checkBalance(coins[0], function(err){
          var tail;
          expect(err).toBe(null);
          tail = p.tail(
          coins);
          if (tail.length === 0) {
            return cb(null);
          }
          checkBalances(tail, function(err){
            expect(err).toBe(null);
            cb(err);
          });
        });
      };
      checkBalances(allCoins, function(err){
        expect(err).toBe(null);
        done(null);
      });
    });
    return it('rates', function(done){
      var coins, checkRate, checkRates;
      this.timeout(5000);
      coins = allCoins;
      checkRate = function(coin, cb){
        var provider;
        provider = main.rate[coin];
        return provider(function(err, rate){
          expect(err).toBe(null);
          expect(rate).toBeA('number');
          cb(null, rate);
        });
      };
      checkRates = function(arg$, cb){
        var head, tail;
        head = arg$[0], tail = slice$.call(arg$, 1);
        if (head == null) {
          return cb(null);
        }
        return checkRate(head, function(err){
          expect(err).toBe(null);
          checkRates(tail, cb);
        });
      };
      return checkRates(coins, done);
    });
  });
}).call(this);
