// Generated by LiveScript 1.5.0
(function(){
  var expect, main, big, p, moment, allCoins, slice$ = [].slice;
  expect = require('expect');
  main = require('../main/main.js');
  big = require('big.js');
  p = require('prelude-ls');
  moment = require('moment');
  allCoins = ['eth', 'btc', 'ltc'];
  describe('Rate', function(run){
    var _;
    _ = JSON.stringify;
    it('set-rate-index', function(done){
      var obj, another;
      obj = "test";
      main.rateHistory.setRateIndex('TEST', obj);
      another = main.rateHistory.getRateIndex('TEST');
      expect(obj === "test").toBe(true);
      return done();
    });
    it('rate-index-create', function(done){
      var toDate, startCampaignDate, buyOrSell, currencyPair, keys;
      this.timeout(90000);
      toDate = new Date().getTime() / 1000;
      startCampaignDate = toDate - 20 * 60 * 60;
      buyOrSell = 'buy';
      currencyPair = 'BTC_ETH';
      keys = function(){
        return Object.keys(main.rateHistory.rateIndex).length;
      };
      expect(keys()).toBe(0);
      return main.rateHistory.createRateIndex({
        startCampaignDate: startCampaignDate,
        buyOrSell: buyOrSell,
        currencyPair: currencyPair,
        toDate: toDate
      }, function(err){
        expect(err).toBe(null);
        expect(keys()).toBeGreaterThan(0);
        done();
      });
    });
    it('use-index', function(done){
      var keys;
      keys = function(){
        return Object.keys(main.rateHistory.rateIndex).length;
      };
      expect(keys()).toBeGreaterThan(0);
      return done();
    });
    it('validate-index', function(done){
      var index;
      index = main.rateHistory.rateIndex;
      console.log(index);
      return done();
    });
    return;
    it('rate-history-0', function(done){
      this.timeout(25000);
      return main.rateHistory.getRate("2017-05-28 4:30:00", function(err, result){
        expect(_(result)).toBe(_({
          ETH: {
            BTC: '0.07846300',
            CHF: '167.00000000'
          }
        }));
        done();
      });
    });
    it('rate-history-1', function(done){
      this.timeout(15000);
      return main.rateHistory.getRate("2017-05-30 4:30:00", function(err, result){
        expect(_(result)).toBe(_({
          ETH: {
            BTC: '0.08900010',
            CHF: '199.50000001'
          }
        }));
        done();
      });
    });
    it('rate-history-2', function(done){
      this.timeout(15000);
      return main.rateHistory.getRate("2017-06-01 4:30:00", function(err, result){
        expect(_(result)).toBe(_({
          ETH: {
            BTC: '0.09699600',
            CHF: '219.46044850'
          }
        }));
        done();
      });
    });
    it('rate-history-3', function(done){
      this.timeout(15000);
      return main.rateHistory.getRate("2017-06-01 22:30:00", function(err, result){
        expect(_(result)).toBe(_({
          ETH: {
            BTC: '0.09276898',
            CHF: '211.50000000'
          }
        }));
        done();
      });
    });
    it('rate-history-3-duplicate', function(done){
      this.timeout(15000);
      return main.rateHistory.getRate("2017-06-01 22:30:00", function(err, result){
        expect(_(result)).toBe(_({
          ETH: {
            BTC: '0.09276898',
            CHF: '211.50000000'
          }
        }));
        done();
      });
    });
    it('rate-history-4', function(done){
      this.timeout(8000);
      return main.rateHistory.getRate("2017-06-01 23:30:00", function(err, result){
        expect(_(result)).toBe(_({
          ETH: {
            BTC: '0.09198971',
            CHF: '211.30000058'
          }
        }));
        done();
      });
    });
    it('rate-history-4-duplicate', function(done){
      this.timeout(8000);
      return main.rateHistory.getRate("2017-06-01 23:30:00", function(err, result){
        expect(_(result)).toBe(_({
          ETH: {
            BTC: '0.09198971',
            CHF: '211.30000058'
          }
        }));
        done();
      });
    });
    it('rates-cryptocompare', function(done){
      var coins, checkRate, checkRates;
      this.timeout(5000);
      coins = allCoins;
      checkRate = function(coin, cb){
        var provider;
        provider = main.rate[coin];
        return provider(function(err, rate){
          expect(err).toBe(null);
          expect(rate).toBeA('number');
          cb(null, rate);
        });
      };
      checkRates = function(arg$, cb){
        var head, tail;
        head = arg$[0], tail = slice$.call(arg$, 1);
        if (head == null) {
          return cb(null);
        }
        return checkRate(head, function(err){
          expect(err).toBe(null);
          checkRates(tail, cb);
        });
      };
      return checkRates(coins, done);
    });
  });
}).call(this);
