// Generated by LiveScript 1.5.0
(function(){
  var expect, main;
  expect = require('expect');
  main = require('../main/main.js');
  describe('Encrypt', function(){
    return it('basic', function(done){
      var t, message;
      this.timeout(10000);
      t = main.encryptPrivateKey;
      message = "5KN7MzqK5wt2TP1fQCYyHBtDrXdJuXbUzm4A9rKAteGu3Qi5CVR";
      return t.genpass(function(err, key){
        expect(err).toBe(null);
        t.encrypt(message, key, function(err, encrypted){
          expect(err).toBe(null);
          t.decrypt(encrypted, key, function(err, decrypted){
            expect(err).toBe(null);
            expect(decrypted).toBe(message);
            done();
          });
        });
      });
    });
  });
}).call(this);
