// Generated by LiveScript 1.5.0
(function(){
  var main, bigNumber, expect;
  main = require('../main/main.js');
  bigNumber = require('big-number');
  expect = require('expect');
  describe('Totals', function(){
    it('empty', function(done){
      var total;
      this.timeout(5000);
      total = main.total(main.rate);
      return total.totals(function(result){
        var i$, ref$, len$, detail;
        expect(result.totalUsd).toBe('0');
        expect(result.details.length).toBe(3);
        for (i$ = 0, len$ = (ref$ = result.details).length; i$ < len$; ++i$) {
          detail = ref$[i$];
          expect(detail.amount).toBe('0');
          expect(detail.amountUsd).toBe('0');
          expect(detail.rate).toBeGreaterThan(0);
        }
        done();
      });
    });
    return it('static-rate', function(done){
      var getRate, total;
      getRate = function(callback){
        return callback(1);
      };
      total = main.total({
        btc: getRate,
        ltc: getRate,
        eth: getRate
      });
      return total.totals(function(result){
        var i$, ref$, len$, detail;
        expect(result.totalUsd).toBe('0');
        expect(result.details.length).toBe(3);
        for (i$ = 0, len$ = (ref$ = result.details).length; i$ < len$; ++i$) {
          detail = ref$[i$];
          expect(detail.amount).toBe('0');
          expect(detail.amountUsd).toBe('0');
          expect(detail.rate).toBe(1);
        }
        done();
      });
    });
  });
}).call(this);
