// Generated by LiveScript 1.5.0
(function(){
  var bitcore, Message;
  bitcore = require('bitcore-lib');
  Message = require('bitcore-message');
  module.exports = {
    sign: function(message, privateKey){
      var key;
      key = bitcore.PrivateKey(privateKey);
      return Message(message).sign(key);
    },
    verify: function(message, address, signature){
      return Message(message).verify(address, signature);
    }
  };
}).call(this);
