// Generated by LiveScript 1.5.0
(function(){
  var slackWebhook, slack;
  slackWebhook = require('slack-webhook');
  slack = new slackWebhook('https://hooks.slack.com/services/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', {
    defaults: {
      username: 'Bot',
      channel: '#bot',
      icon_emoji: ':robot_face:'
    }
  });
  module.exports = curry$(function(serviceName, err, details){
    var errDetails, ref$;
    if (err != null) {
      if (details != null) {
        errDetails = "; " + details;
      }
      slack.send("[" + serviceName + "] Error: " + ((ref$ = err.message) != null ? ref$ : err) + errDetails);
    }
    return err != null;
  });
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
