// Generated by LiveScript 1.5.0
(function(){
  var ref$, out$ = typeof exports != 'undefined' && exports || this;
  ref$ = out$;
  ref$.newAddr = {
    eth: require('./new-addr/new-addr-eth.js'),
    btc: require('./new-addr/new-addr-btc.js'),
    ltc: require('./new-addr/new-addr-ltc.js')
  };
  ref$.sign = {
    eth: require('./sign/sign-eth.js'),
    btc: require('./sign/sign-btc.js'),
    ltc: require('./sign/sign-ltc.js')
  };
  ref$.balance = {
    ltc: require('./balance/balance-ltc.js'),
    btc: require('./balance/balance-btc.js'),
    eth: require('./balance/balance-eth.js')
  };
  ref$.rate = {
    ltc: require('./rate/rate.js')('LTC'),
    btc: require('./rate/rate.js')('BTC'),
    eth: require('./rate/rate.js')('ETH')
  };
}).call(this);
