// Generated by LiveScript 1.5.0
(function(){
  var ref$, out$ = typeof exports != 'undefined' && exports || this;
  ref$ = out$;
  ref$.newAddr = {
    eth: require('./new-addr-eth.js'),
    btc: require('./new-addr-btc.js'),
    ltc: require('./new-addr-ltc.js')
  };
  ref$.sign = {
    eth: require('./sign-eth.js'),
    btc: require('./sign-btc.js'),
    ltc: require('./sign-ltc.js')
  };
  ref$.balance = {
    ltc: require('./balance-ltc.js'),
    btc: require('./balance-btc.js'),
    eth: require('./balance-eth.js')
  };
}).call(this);
