// Generated by LiveScript 1.5.0
(function(){
  var request, bigNumber;
  request = require('request');
  bigNumber = require('big-number');
  module.exports = curry$(function(name, callback){
    return request("https://min-api.cryptocompare.com/data/price?fsym=" + name + "&tsyms=USD", function(err, response, body){
      var data, e;
      if (err != null) {
        return callback(null);
      }
      try {
        data = JSON.parse(body);
        callback(data.USD);
      } catch (e$) {
        e = e$;
        callback(null);
      }
    });
  });
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
