// Generated by LiveScript 1.5.0
(function(){
  module.exports = {
    sign: function(message, privateKey){
      return message;
    },
    verify: function(message, address, signature){
      return message === message;
    }
  };
}).call(this);
