// Generated by LiveScript 1.5.0
(function(){
  var go, slice$ = [].slice;
  go = curry$(function(strategies, key, callback){
    var head, tail;
    head = strategies[0], tail = slice$.call(strategies, 1);
    if (head == null) {
      return callback(null);
    }
    return head(key, function(result){
      if (result !== null) {
        return callback(result);
      }
      go(tail, key, function(nextResult){
        callback(nextResult);
      });
    });
  });
  module.exports = go;
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
